# These will be sorted first in that order.
# All packages that are depended upon by others should be listed here.
[DEFAULT]

sortfirst=
    util/opentelemetry-util-genai
    instrumentation/*

[prerelease]
version=0.63b0.dev

packages=
    all
    opentelemetry-util-genai

[exclude_release]
packages=
    opentelemetry-instrumentation-anthropic
    opentelemetry-instrumentation-claude-agent-sdk
    opentelemetry-instrumentation-google-genai
    opentelemetry-instrumentation-langchain
    opentelemetry-instrumentation-openai-v2
    opentelemetry-instrumentation-openai-agents-v2
    opentelemetry-instrumentation-weaviate
    opentelemetry-util-genai

[lintroots]
extraroots=examples/*,scripts/
subglob=*.py,tests/,test/,src/*,examples/*

[testroots]
extraroots=examples/*,tests/
subglob=tests/,test/
